export const EVENT_TYPES = {
  TENANT_CREATED:
    'TENANT.CREATED',

  TENANT_DELETED:
    'TENANT.DELETED',

  TENANT_UPDATED:
    'TENANT.UPDATED',

  TENANT_USER_ADDED:
    'TENANT.USER_ADDED',

  TENANT_USER_REMOVED:
    'TENANT.USER_REMOVED',

  PLAN_UPGRADED:
    'PLAN.UPGRADED',

  PLAN_DOWNGRADED:
    'PLAN.DOWNGRADED',

  INVITATION_SENT:
    'INVITATION.SENT',

  INVITATION_ACCEPTED:
    'INVITATION.ACCEPTED',

  WEBHOOK_DELIVERY_FAILED:
    'WEBHOOK.DELIVERY_FAILED',
} as const;